IF db_id('MAJSTERKLEPKA') IS NULL
CREATE DATABASE MAJSTERKLEPKA;

GO

USE MAJSTERKLEPKA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PRODUKTY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.PRODUKTY;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ZAMOWIENIA' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.ZAMOWIENIA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ZAMOWIENIE_SZ' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.ZAMOWIENIE_SZ;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='DOSTAWCY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.DOSTAWCY;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='KATEGORIA' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.KATEGORIA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='KLIENCI' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.KLIENCI;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PRACOWNICY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.PRACOWNICY;

CREATE TABLE PRODUKTY 
(
ID_PRODUKT INT IDENTITY NOT NULL,
ID_DOSTAWCA INT,
ID_KATEGORIA INT,
NAZWA_PRODUKTU VARCHAR,
STAN INT,
CENA_NETTO INT,
CENA_BRUTTO INT,
INFORMACJE VARCHAR,
GWARANCJA INT  

PRIMARY KEY (ID_PRODUKT)
)

CREATE TABLE ZAMOWIENIA 
(
ID_ZAMOWIENIE INT IDENTITY UNIQUE NOT NULL,
ID_KLIENT INT,
ID_PRACOWNIK INT,
CZAS DATE,
FAKTURA BIT

PRIMARY KEY (ID_ZAMOWIENIE) 
)

CREATE TABLE ZAMOWIENIE_SZ (
ID_ZAMOWIENIE INT IDENTITY(1,1) NOT NULL,
ID_PRODUKT INT,
CENA INT,
ILOSC INT 

PRIMARY KEY (ID_ZAMOWIENIE) 
)

CREATE TABLE DOSTAWCY (
ID_DOSTAWCA INT IDENTITY NOT NULL,
NAZWA_FIRMY VARCHAR,
ADRES VARCHAR,
MIASTO VARCHAR,
KOD INT,
KRAJ VARCHAR,
TELEFON INT 

PRIMARY KEY (ID_DOSTAWCA)
)

CREATE TABLE KATEGORIA (
ID_KATEGORIA INT IDENTITY NOT NULL,
NAZWA_KATEGORII VARCHAR,
VAT INT 

PRIMARY KEY (ID_KATEGORIA)
)

CREATE TABLE KLIENCI (
ID_KLIENT INT IDENTITY NOT NULL,
KONTAKT INT 

PRIMARY KEY (ID_KLIENT)
)

CREATE TABLE PRACOWNICY (
ID_PRACOWNIK INT IDENTITY  NOT NULL,
STANOWISKO VARCHAR 

PRIMARY KEY (ID_PRACOWNIK)
)

ALTER TABLE PRODUKTY
ADD CONSTRAINT PRODUKTY_KATEGORIA_FK 
FOREIGN KEY (ID_KATEGORIA) REFERENCES dbo.KATEGORIA(ID_KATEGORIA)

ALTER TABLE ZAMOWIENIE_SZ
ADD CONSTRAINT PRODUKTY_ZAMOWIENIA_FK 
FOREIGN KEY (ID_PRODUKT) REFERENCES dbo.PRODUKTY(ID_PRODUKT)

ALTER TABLE PRODUKTY
ADD CONSTRAINT PRODUKTY_DOSTAWCY_FK 
FOREIGN KEY (ID_DOSTAWCA) REFERENCES dbo.DOSTAWCY(ID_DOSTAWCA)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_KLIENT_FK 
FOREIGN KEY (ID_KLIENT) REFERENCES dbo.KLIENCI(ID_KLIENT)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_ID_FK 
FOREIGN KEY (ID_ZAMOWIENIE) REFERENCES dbo.ZAMOWIENIE_SZ(ID_ZAMOWIENIE)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_PRACOWNIK_FK 
FOREIGN KEY (ID_PRACOWNIK) REFERENCES dbo.PRACOWNICY(ID_PRACOWNIK)
